### ISSUE TITLE
Collector for CrowdStrike Endpoint Security

### ISSUE THREAD

**Issue by SamuelHassine** [OpenBAS-Platform/collectors#11]
## Use case

Collector for CrowdStrike Endpoint Security

**Comment by jborozco** [comment]
Paused until we have access from the tech alliance

**Comment by annoyingapt** [comment]
Is the intention to integrate with Crowdstrike's next gen siem, or limit it to the edr product?

**Comment by jborozco** [comment]
@annoyingapt We may start with the EDR, but we'll cover both, do you have a specific need for SIEM ?

**Comment by annoyingapt** [comment]
I'm just starting on our OpenBAS journey, just trying to get my head around things. Yeah we have an interest in their siem product, not just edr.
