### ISSUE TITLE
Remove hostname matching on Microsoft Defender

### ISSUE THREAD

**Issue by RomuDeuxfois** [OpenBAS-Platform/collectors#85]
## Description

Initially, we decided to match the alerts we collect on the hostname and other properties.
Then, we moved on to matching the process name of the implant to be as precise as possible.
However, we left the matching on the hostname and this poses problems in the case where we have FQDNs.

The idea here is to simply remove the matching on the hostname, as we have already done for Sentinel and Crowdstrike.

**Comment by antoinemzs** [comment]
Note that we never log the FQDN in OpenBAS, just the hostname. Since process name matching is based on a UUIDv4 it's reasonable to not bother with matching hostnames.
