### ISSUE TITLE
Rework Tanium Threat Response collector to work with process name signature

### ISSUE THREAD

**Issue by RomuDeuxfois** [OpenBAS-Platform/collectors#86]
## Description

Initially, we decided to match the alerts we collect on the hostname and other properties.
Then, we moved on to matching the process name of the implant to be as precise as possible.

We forget to align this collector with the new mechanism, so it no longer works.

**Comment by RomuDeuxfois** [comment]
~~Blocked by https://github.com/OpenBAS-Platform/client-python/pull/68~~

**Comment by antoinemzs** [comment]
We should just make it work as-is and not block it pending a pyobas refactoring
